export const time_zone = [
	{ value: 'ESD', name: 'Eastern Standard Time' },
	{ value: 'CSD', name: 'Central Standard Time' },
	{ value: 'MST', name: 'Mountain Standard Time' },
	{ value: 'PST', name: 'Pacific Standard Time' },
	{ value: 'AKST', name: 'Alaska Standard Time' },
	{ value: 'HST', name: 'Hawaii Standard Time' },
	{ value: 'GMT', name: 'Greenwich Mean Time' },
	{ value: 'BST', name: 'British Summer Time' },
	{ value: 'CET', name: 'Central European Time' },
	{ value: 'EET', name: 'Eastern European Time' },
	{ value: 'IST', name: 'India Standard Time' },
	{ value: 'JST', name: 'Japan Standard Time' },
	{ value: 'NZST', name: 'New Zealand Standard Time' },
	{ value: 'WST', name: 'Western Standard Time' },
	{ value: 'AEST', name: 'Australian Eastern Standard Time' },
	{ value: 'ACST', name: 'Australian Central Standard Time' },
	{ value: 'AWST', name: 'Australian Western Standard Time' },
	{ value: 'ACDT', name: 'Australian Central Daylight Time' },
	{ value: 'AEDT', name: 'Australian Eastern Daylight Time' },
	{ value: 'AWDT', name: 'Australian Western Daylight Time' },
	{ value: 'NZDT', name: 'New Zealand Daylight Time' },
	{ value: 'NZST', name: 'New Zealand Standard Time' },

];